### PR TITLE
Post text

### PR DESCRIPTION
**Pull request by mickhansen**

### CODE REVIEW

**Comment by sgryt** [comment]
I still have an HTTP GET to the /sign/text endpoint when the text is larger than 500 bytes (according to Fiddler, at least). Do I need to do anything else than build and run the project in VS Code ?

**Comment by mickhansen** [comment]
I just check string length of the base64 encoded value, so not sure what the exact byte cutoff would be. I just take an entire Bacon Ipsum section to test

**Comment by sgryt** [comment]
The API seems to behave as expected, but the SPA still creates an HTTP GET - I had expected an auto-submitting form ?

**Comment by mickhansen** [comment]
@sgryt It should be auto submitting a form to a new tab in the case of larger texts

**Comment by mickhansen** [comment]
Uh i may have forgotten `action="POST` actually.

**Comment by mickhansen** [comment]
Give it another spin please @sgryt

**Pull request merged**
